import { MapMarker } from "@/types";

export const markersMezaninoSuperior: MapMarker[] = [
    {
        id: "1",
        name: "Laboratório Informática",
        description: "Um espaço equipado com computadores, destinado à aulas de informática - Sala 17 e 18",
        x: 12.72,
        y: 32.13,
        category: "Aulas Informática",
        color: "bg-green-900",
        visible: true,
    },
    {
        id: "2",
        name: "Escadaria ",
        description: "Escadaria que dá acesso ao mezanino e térreo",
        x: 16.47,
        y: 37.13,
        category: "Acesso",
        color: "bg-blue-500",
        visible: true,
    },
    {
        id: "3",
        name: "Laboratório Informática",
        description: "Um espaço equipado com computadores, destinado à aulas de informática - Sala 19",
        x: 13.3,
        y: 53.25,
        category: "Aulas Informática",
        color: "bg-green-900",
        visible: true,
    },
    {
        id: "4",
        name: "Laboratório Informática",
        description: "Um espaço equipado com computadores, destinado à aulas de informática - Sala 20, 21 e 22",
        x: 13.8,
        y: 65.13,
        category: "Aulas Informática",
        color: "bg-green-900",
        visible: true,
    },
    {
        id: "5",
        name: "Escadaria ",
        description: "Escadaria que dá acesso ao mezanino e térreo",
        x: 37.22,
        y: 25.5,
        category: "Acesso",
        color: "bg-blue-500",
        visible: true,
    },
    {
        id: "6",
        name: "Banheiros",
        description: "Sanitários masculino e feminino",
        x: 23.55,
        y: 43,
        category: "Sanitário",
        color: "bg-gray-500",
        visible: true,
    },
    {
        id: "7",
        name: "Coordenação Aprendizagem",
        description: "Coordenação responsável por menores aprendizes",
        x: 30.8,
        y: 35.13,
        category: "Administrativo Senac",
        color: "bg-orange-900",
        visible: true,
    },
    {
        id: "8",
        name: "Sala 42",
        description: "Ambiente Pedagógico convencional, destinado à aulas teóricas gerais",
        x: 39.22,
        y: 44.5,
        category: "Ambiente Pedagógico",
        color: "bg-gray-900",
        visible: true,
    },
    {
        id: "9",
        name: "Sala 40",
        description: "Ambiente Pedagógico convencional, destinado à aulas teóricas gerais",
        x: 46.72,
        y: 44.5,
        category: "Ambiente Pedagógico",
        color: "bg-gray-900",
        visible: true,
    },
    {
        id: "10",
        name: "Elevador",
        description: "Elevador direto Térreo x Mezanino Superior",
        x: 52.92,
        y: 24.13,
        category: "Acesso",
        color: "bg-blue-500",
        visible: true,
    },
    {
        id: "11",
        name: "Banheiros",
        description: "Sanitários masculino e feminino",
        x: 56.34,
        y: 43,
        category: "Sanitário",
        color: "bg-gray-500",
        visible: true,
    },
    {
        id: "12",
        name: "Sala 39",
        description: "Ambiente Pedagógico convencional, destinado à aulas teóricas gerais",
        x: 60.59,
        y: 44.5,
        category: "Ambiente Pedagógico",
        color: "bg-gray-900",
        visible: true,
    },
    {
        id: "13",
        name: "Sala 38",
        description: "Ambiente Pedagógico convencional, destinado à aulas teóricas gerais",
        x: 65.6,
        y: 44.5,
        category: "Ambiente Pedagógico",
        color: "bg-gray-900",
        visible: true,
    },
    {
        id: "14",
        name: "Sala 37",
        description: "Ambiente Pedagógico convencional, destinado à aulas teóricas gerais",
        x: 73.25,
        y: 44.5,
        category: "Ambiente Pedagógico",
        color: "bg-gray-900",
        visible: true,
    },
    {
        id: "15",
        name: "Sala 36",
        description: "Ambiente Pedagógico convencional, destinado à aulas teóricas gerais",
        x: 78,
        y: 30.75,
        category: "Ambiente Pedagógico",
        color: "bg-gray-900",
        visible: true,
    },
    {
        id: "16",
        name: "Sala 34 e Sala 35",
        description: "Ambientes Pedagógicos convencionais, destinados à aulas teóricas gerais",
        x: 84.25,
        y: 31.25,
        category: "Ambiente Pedagógico",
        color: "bg-gray-900",
        visible: true,
    },
    {
        id: "18",
        name: "Sala 33",
        description: "Ambiente Pedagógico convencional, destinado à aulas teóricas gerais",
        x: 91.09,
        y: 32.13,
        category: "Ambiente Pedagógico",
        color: "bg-gray-900",
        visible: true,
    },
    {
        id: "19",
        name: "",
        description: "Acesso Restrito",
        x: 91.34,
        y: 43.5,
        category: "Restrito",
        color: "bg-red-500",
        visible: true,
    },
    {
        id: "20",
        name: "",
        description: "Acesso Restrito",
        x: 87.34,
        y: 45.74,
        category: "Restrito",
        color: "bg-red-500",
        visible: true,
    },
    {
        id: "21",
        name: "",
        description: "Acesso Restrito",
        x: 87.34,
        y: 53.88,
        category: "Restrito",
        color: "bg-red-500",
        visible: true,
    },
    {
        id: "22",
        name: "",
        description: "Acesso Restrito",
        x: 87.34,
        y: 60.88,
        category: "Restrito",
        color: "bg-red-500",
        visible: true,
    },
    {
        id: "23",
        name: "Escadaria ",
        description: "Escadaria que dá acesso ao mezanino e térreo",
        x: 93.09,
        y: 66.88,
        category: "Acesso",
        color: "bg-blue-500",
        visible: true,
    },
    {
        id: "24",
        name: "Jardim de inverno",
        description: "Um ambiente interno todo voltado ao contato com a natureza.",
        x: 23,
        y: 57.38,
        category: "Jardim",
        color: "bg-emerald-300",
        visible: true,
    },
    {
        id: "25",
        name: "Sala 41",
        description: "Ambiente Pedagógico convencional, destinado à aulas teóricas gerais",
        x: 37.25,
        y: 49.25,
        category: "Ambiente Pedagógico",
        color: "bg-gray-900",
        visible: true,
    },
    {
        id: "26",
        name: "",
        description: "Acesso Restrito",
        x: 41.34,
        y: 61.5,
        category: "Restrito",
        color: "bg-red-500",
        visible: true,
    },
    {
        id: "27",
        name: "",
        description: "Acesso Restrito",
        x: 53.5,
        y: 57.25,
        category: "Restrito",
        color: "bg-red-500",
        visible: true,
    },
    {
        id: "28",
        name: "Auditório João Daudt d' Oliveira",
        description: "Espaço equipado para eventos, palestras e apresentações, com estrutura moderna, conforto e recursos audiovisuais.",
        x: 65,
        y: 57.38,
        category: "Auditório",
        color: "bg-cyan-500",
        visible: true,
    },
    {
        id: "29",
        name: "Sala 23 e Sala 24",
        description: "Ambientes Pedagógicos convencionais, destinados à aulas teóricas gerais",
        x: 32.34,
        y: 68.63,
        category: "Ambiente Pedagógico",
        color: "bg-gray-900",
        visible: true,
    },
    {
        id: "30",
        name: "Sala 25",
        description: "Ambiente Pedagógico convencional, destinado à aulas teóricas gerais",
        x: 39.75,
        y: 68.63,
        category: "Ambiente Pedagógico",
        color: "bg-gray-900",
        visible: true,
    },
    {
        id: "31",
        name: "Sala 26 e Sala 27",
        description: "Ambientes Pedagógicos convencionais, destinados à aulas teóricas gerais",
        x: 49.92,
        y: 68.63,
        category: "Ambiente Pedagógico",
        color: "bg-gray-900",
        visible: true,
    },
    {
        id: "32",
        name: "Sala 28",
        description: "Ambiente Pedagógico convencional, destinado à aulas teóricas gerais",
        x: 57.9,
        y: 68.63,
        category: "Ambiente Pedagógico",
        color: "bg-gray-900",
        visible: true,
    },
    {
        id: "33",
        name: "Sala 29",
        description: "Ambiente Pedagógico convencional, destinado à aulas teóricas gerais",
        x: 63.17,
        y: 68.63,
        category: "Ambiente Pedagógico",
        color: "bg-gray-900",
        visible: true,
    },
    {
        id: "34",
        name: "Sala 30",
        description: "Ambiente Pedagógico convencional, destinado à aulas teóricas gerais",
        x: 69.17,
        y: 68.63,
        category: "Ambiente Pedagógico",
        color: "bg-gray-900",
        visible: true,
    },
    {
        id: "35",
        name: "Tecnico Raio X",
        description: "Ambiente destinado à formação prática e teórica de profissionais em Radiologia, equipado com simuladores e recursos que reproduzem procedimentos de diagnóstico por imagem - Sala 31",
        x: 75,
        y: 68.63,
        category: "Aulas Saúde",
        color: "bg-violet-500",
        visible: true,
    },
    {
        id: "36",
        name: "Práticas de Enfermagem",
        description: "Espaço estruturado para o desenvolvimento de habilidades práticas em Enfermagem, com equipamentos e materiais que simulam ambientes hospitalares e de atenção à saúde.",
        x: 87,
        y: 68.63,
        category: "Aulas Saúde",
        color: "bg-violet-500",
        visible: true,
    }
];
