import { MapMarker } from "@/types";

export const markersL4: MapMarker[] = [
  {
    id: "1",
    name: "Estética",
    description:
      "Espaço destinado ao ensino teórico e prático de procedimentos estéticos - sala 401 402 403",
    x: 7.13,
    y: 34.88,
    category: "Aulas Beleza",
    color: "bg-pink-400",
    visible: true,
    video: 'nu2TyRK3VKo'
  },
  {
    id: "2",
    name: "Sala 404",
    description:
      "Ambiente Pedagógico convencional, destinado à aulas teóricas gerais",
    x: 14.38,
    y: 46.38,
    category: "Ambiente Pedagógico",
    color: "bg-gray-900",
    visible: true,
  },
  {
    id: "3",
    name: "Fotografia",
    description:
      "Espaço destinado ao ensino teórico e prático de fotografia - sala 405",
    x: 25.8,
    y: 46.38,
    category: "Aulas Fotografia",
    color: "bg-rose-950",
    visible: true,
  },
  {
    id: "4",
    name: "Escada",
    description: "Escada acesso geral Ed. João Daud't",
    x: 35.97,
    y: 46.75,
    category: "Acesso",
    color: "bg-blue-500",
    visible: true,
  },
  {
    id: "5",
    name: "Banheiro",
    description: "Sanitários masculino e feminino",
    x: 40.22,
    y: 49.75,
    category: "Sanitário",
    color: "bg-gray-500",
    visible: true,
  },
  {
    id: "6",
    name: "Ambiente de Treinamento para Competição – Florista",
    description:
      "Espaço dedicado ao treino prático e simulações de provas, preparando os alunos para competições na área de arte floral - sala 406",
    x: 47.05,
    y: 39.5,
    category: "Competição",
    color: "bg-[#D4AF37]",
    visible: true,
    video: 'GQoDWi-Kev4'
  },
  {
    id: "7",
    name: "Sala 407",
    description:
      "Ambiente Pedagógico convencional, destinado à aulas teóricas gerais",
    x: 52.13,
    y: 51,
    category: "Ambiente Pedagógico",
    color: "bg-gray-900",
    visible: true,
  },
  {
    id: "8",
    name: "Sala 408",
    description:
      "Ambiente Pedagógico convencional, destinado à aulas teóricas gerais",
    x: 60.94,
    y: 51,
    category: "Ambiente Pedagógico",
    color: "bg-gray-900",
    visible: true,
  },
  {
    id: "9",
    name: "Sala 409",
    description:
      "Ambiente Pedagógico convencional, destinado à aulas teóricas gerais",
    x: 69.77,
    y: 51,
    category: "Ambiente Pedagógico",
    color: "bg-gray-900",
    visible: true,
  },
  {
    id: "10",
    name: "Sala 410",
    description:
      "Ambiente Pedagógico convencional, destinado à aulas teóricas gerais",
    x: 78.77,
    y: 51,
    category: "Ambiente Pedagógico",
    color: "bg-gray-900",
    visible: true,
  },
  {
    id: "11",
    name: "Sala 411",
    description:
      "Ambiente Pedagógico convencional, destinado à aulas teóricas gerais",
    x: 87.52,
    y: 51,
    category: "Ambiente Pedagógico",
    color: "bg-gray-900",
    visible: true,
  },
  {
    id: "12",
    name: "Escada Emergência",
    description: "Escada emergência Ed. João Daud't",
    x: 83.94,
    y: 57.38,
    category: "Acesso",
    color: "bg-blue-500",
    visible: true,
  },
  {
    id: "13",
    name: "Elevador",
    description: "Elevador acesso geral Ed. João Daud't",
    x: 38.88,
    y: 59.5,
    category: "Acesso",
    color: "bg-blue-500",
    visible: true,
  },
  {
    id: "14",
    name: "Rampa",
    description: "Rampa acesso geral Ed. João Daud't",
    x: 21.88,
    y: 54.5,
    category: "Acesso",
    color: "bg-blue-500",
    visible: true,
  },
  {
    id: "15",
    name: "Massoterapia",
    description:
      "Espaço destinado ao ensino teórico e prático de massoterapia - sala 401 402 403",
    x: 7.13,
    y: 54.5,
    category: "Massoterapia",
    color: "bg-emerald-600",
    visible: true,
    video: 'nu2TyRK3VKo?start=68&'
  },
];
