import { MapMarker } from "@/types";

export const markersL2: MapMarker[] = [
    {
        id: "1",
        name: "",
        description: "A partir desse ponto acesso restrito, somente funcionários.",
        x: 10.72,
        y: 52.2,
        category: "Restrito",
        color: "bg-red-500",
        visible: true,
    },
    {
        id: "2",
        name: "Secretaria de Apoio Logístico",
        description:
            "Responsável por tirar dúvidas, fornecer informações sobre o prédio e gerenciar achados e perdidos, garantindo suporte eficiente para alunos, professores e colaboradores.",
        x: 19.63,
        y: 45.88,
        category: "Administrativo Senac",
        color: "bg-orange-900",
        visible: true,
    },
    {
        id: "3",
        name: "Rampa",
        description: "Rampa acesso geral Ed. João Daud't",
        x: 25.05,
        y: 58.13,
        category: "Acesso",
        color: "bg-blue-500",
        visible: true,
    },
    {
        id: "4",
        name: "Banheiro",
        description: "Sanitários masculino e feminino",
        x: 37.97,
        y: 51.63,
        category: "Sanitário",
        color: "bg-gray-500",
        visible: true,
    },
    {
        id: "5",
        name: "Escada",
        description: "Escada acesso geral Ed. João Daud't",
        x: 33.63,
        y: 46,
        category: "Acesso",
        color: "bg-blue-500",
        visible: true,
    },
    {
        id: "6",
        name: "Elevador",
        description: "Elevador acesso geral Ed. João Daud't",
        x: 36.08,
        y: 63.38,
        category: "Acesso",
        color: "bg-blue-500",
        visible: true,
    },
    {
        id: "7",
        name: "",
        description: "A partir desse ponto acesso restrito, somente funcionários.",
        x: 43.63,
        y: 53,
        category: "Restrito",
        color: "bg-red-500",
        visible: true,
    },
    {
        id: "8",
        name: "Gerência",
        description:
            "Órgão responsável pela coordenação administrativa e estratégica da unidade, garantindo a qualidade dos serviços, o cumprimento das metas e o alinhamento com as diretrizes institucionais.",
        x: 52.08,
        y: 49.75,
        category: "Administrativo Senac",
        color: "bg-orange-900",
        visible: true,
    },
    {
        id: "9",
        name: "Escada Emergência",
        description: "Escada emergência Ed. João Daud't",
        x: 53.63,
        y: 62.05,
        category: "Acesso",
        color: "bg-blue-500",
        visible: true,
    },
    {
        id: "10",
        name: "Coordenação Cursos Livres",
        description:
            "Responsável pela gestão, organização e supervisão dos cursos livres, garantindo a qualidade pedagógica e o atendimento às necessidades dos alunos e do mercado.",
        x: 66.47,
        y: 53.13,
        category: "Administrativo Senac",
        color: "bg-orange-900",
        visible: true,
    },
];