import { MapMarker } from "@/types";

export const markersL3: MapMarker[] = [
    {
        id: "1",
        name: "Radiologia",
        description:
            "Espaço destinado às aulas teóricas e práticas da área de Radiologia, equipado para o desenvolvimento dos conhecimentos técnicos e científicos necessários à formação dos alunos.",
        x: 8.38,
        y: 40.25,
        category: "Aulas Saúde",
        color: "bg-violet-500",
        visible: true,
    },
    {
        id: "2",
        name: "Enfermagem",
        description:
            "Espaço estruturado para o ensino prático e teórico das técnicas de enfermagem, onde os alunos desenvolvem competências para atuar na promoção, prevenção e recuperação da saúde.",
        x: 8.38,
        y: 56.88,
        category: "Aulas Saúde",
        color: "bg-violet-500",
        visible: true,
    },
    {
        id: "3",
        name: "Maquiagem",
        description:
            "Ambiente onde os alunos desenvolvem técnicas de maquiagem social e artística, com atendimento real ao público, sob supervisão docente.",
        x: 18.22,
        y: 48.88,
        category: "Aulas Beleza",
        color: "bg-pink-400",
        visible: true,
    },
    {
        id: "4",
        name: "Depilação",
        description:
            "Conjunto de salas privativas destinadas ao atendimento ao público, onde os alunos praticam técnicas de depilação com foco na higiene, conforto e segurança, sempre sob supervisão profissional.",
        x: 27.47,
        y: 48.88,
        category: "Aulas Beleza",
        color: "bg-pink-400",
        visible: true,
    },
    {
        id: "5",
        name: "Escada",
        description: "Escada acesso geral Ed. João Daud't",
        x: 37.63,
        y: 48.13,
        category: "Acesso",
        color: "bg-blue-500",
        visible: true,
    },
    {
        id: "6",
        name: "Banheiro",
        description: "Sanitários masculino e feminino",
        x: 42.13,
        y: 52.75,
        category: "Sanitário",
        color: "bg-gray-500",
        visible: true,
    },
    {
        id: "7",
        name: "Ambiente de Treinamento para Competição – Saúde",
        description:
            "Espaço dedicado ao treino prático e simulações de provas, preparando os alunos para competições na área de saúde - sala 306",
        x: 48.88,
        y: 43.88,
        category: "Competição",
        color: "bg-[#D4AF37]",
        visible: true,
    },
    {
        id: "8",
        name: "Sala 308",
        description:
            "Ambiente Pedagógico convencional, destinado à aulas teóricas gerais",
        x: 67.11,
        y: 49.75,
        category: "Ambiente Pedagógico",
        color: "bg-gray-900",
        visible: true,
    },
    {
        id: "9",
        name: "Sala 309",
        description:
            "Ambiente Pedagógico convencional, destinado à aulas teóricas gerais",
        x: 76.27,
        y: 49.75,
        category: "Ambiente Pedagógico",
        color: "bg-gray-900",
        visible: true,
    },
    {
        id: "10",
        name: "",
        description: "Acesso restrito",
        x: 81.63,
        y: 55,
        category: "Restrito",
        color: "bg-red-500",
        visible: true,
    },
    {
        id: "11",
        name: "Sala 311",
        description:
            "Ambiente Pedagógico convencional, destinado à aulas teóricas gerais",
        x: 92,
        y: 49.75,
        category: "Ambiente Pedagógico",
        color: "bg-gray-900",
        visible: true,
    },
    {
        id: "12",
        name: "Escada Emergência",
        description: "Escada emergência Ed. João Daud't",
        x: 86.36,
        y: 62,
        category: "Acesso",
        color: "bg-blue-500",
        visible: true,
    },
    {
        id: "13",
        name: "Rampa",
        description: "Rampa acesso geral Ed. João Daud't",
        x: 31.35,
        y: 58.63,
        category: "Acesso",
        color: "bg-blue-500",
        visible: true,
    },
    {
        id: "14",
        name: "Elevador",
        description: "Elevador acesso geral Ed. João Daud't",
        x: 41.27,
        y: 64,
        category: "Acesso",
        color: "bg-blue-500",
        visible: true,
    },
    {
        id: "15",
        name: "Vitrinismo",
        description: "Espaço destinado ao desenvolvimento de projetos de ambientação e exposição visual de produtos - Sala 307",
        x: 57.27,
        y: 53,
        category: "Vitrinismo",
        color: "bg-stone-700",
        visible: true,
    },
];