import { MapMarker } from "@/types";

export const markersTerreo: MapMarker[] = [
  {
    id: "1",
    name: "Entrada Principal",
    description: "Acesso principal do edifício",
    x: 5,
    y: 35,
    category: "Acesso",
    color: "bg-blue-500",
    visible: true,
  },
  {
    id: "2",
    name: "Confeitaria",
    description: "Um espaço equipado com bancadas, fornos e utensílios para aulas práticas de gastronomia",
    x: 14.17,
    y: 26.38,
    category: "Aulas Gastronomia",
    color: "bg-green-500",
    visible: true,
  },
  {
    id: "3",
    name: "Capela",
    description: "Espaço reservado para momentos de reflexão, meditação e práticas religiosas, oferecendo um ambiente tranquilo e acolhedor para alunos, funcionários e visitantes.",
    x: 25.75,
    y: 23.75,
    category: "Capela",
    color: "bg-purple-500",
    visible: true,
  },
  {
    id: "4",
    name: "Vestiários",
    description: "Vestiários masculino e feminino",
    x: 33,
    y: 25,
    category: "Vestiário",
    color: "bg-orange-500",
    visible: true,
  },
  {
    id: "5",
    name: "Banheiros",
    description: "Sanitários masculinos e femininos",
    x: 51,
    y: 59,
    category: "Sanitário",
    color: "bg-gray-500",
    visible: true,
  },
  {
    id: "6",
    name: "Banheiro Feminino",
    description: "Sanitário Feminino",
    x: 39,
    y: 29,
    category: "Sanitário",
    color: "bg-gray-500",
    visible: true,
  },
  {
    id: "7",
    name: "",
    description: "A partir deste ponto: acesso restrito, somente funcionários.",
    x: 42,
    y: 33,
    category: "Restrito",
    color: "bg-red-500",
    visible: true,
  },
  {
    id: "8",
    name: "Recepção/Portaria",
    description: "Recepção",
    x: 15,
    y: 37,
    category: "Acesso",
    color: "bg-blue-500",
    visible: true,
  },
  {
    id: "9",
    name: "Escada Auditório",
    description: "Escadaria que dá acesso ao auditório",
    x: 21.67,
    y: 44,
    category: "Acesso",
    color: "bg-blue-500",
    visible: true,
  },
  {
    id: "10",
    name: "Elevador",
    description: "Elevador de acesso exclusivo ao mezanino superior(auditório)",
    x: 49.17,
    y: 43.75,
    category: "Acesso",
    color: "bg-blue-500",
    visible: true,
  },
  {
    id: "11",
    name: "Café do Paço",
    description: "Espaço para pausa, convivência e alimentação com café e lanches.",
    x: 70.49,
    y: 46.25,
    category: "Alimentação",
    color: "bg-yellow-500",
    visible: true,
  },
  {
    id: "12",
    name: "Escada Mezanino",
    description: "Escada que dá acesso ao mezanino",
    x: 6.58,
    y: 49.75,
    category: "Acesso",
    color: "bg-blue-500",
    visible: true,
  },
  {
    id: "13",
    name: "Central de Matrículas",
    description: "Local responsável pelo atendimento e suporte aos alunos para processos de matrícula, rematrícula e informações acadêmicas.",
    x: 14.33,
    y: 56.5,
    category: "Secretaria",
    color: "bg-orange-900",
    visible: true,
  },
  {
    id: "14",
    name: "Biblioteca",
    description: "Espaço reservado para estudo, pesquisa e leitura, oferecendo um ambiente tranquilo com acervo diversificado para apoio acadêmico.",
    x: 30.58,
    y: 63,
    category: "Biblioteca",
    color: "bg-indigo-600",
    visible: true,
  },
  {
    id: "15",
    name: "Secretaria Escolar",
    description: "Acesso restrito, somente atendimentos telefonicos",
    x: 15.92,
    y: 66.5,
    category: "Restrito",
    color: "bg-red-500",
    visible: true,
  },
  {
    id: "16",
    name: "Escada",
    description: "Escada que dá acesso à coordenação gastronomia e café bar",
    x: 21.75,
    y: 63.63,
    category: "Acesso",
    color: "bg-blue-500",
    visible: true,
  },
  {
    id: "17",
    name: "",
    description: "A partir deste ponto: acesso restrito, somente funcionários.",
    x: 56.6,
    y: 64.5,
    category: "Restrito",
    color: "bg-red-500",
    visible: true,
  },
  {
    id: "18",
    name: "Escada Rouparia",
    description: "Escada que dá acesso à rouparia",
    x: 60,
    y: 69,
    category: "Acesso",
    color: "bg-blue-500",
    visible: true,
  },
  {
    id: "19",
    name: "",
    description: "A partir deste ponto: acesso restrito, somente funcionários.",
    x: 66.68,
    y: 77.5,
    category: "Restrito",
    color: "bg-red-500",
    visible: true,
  },
  {
    id: "20",
    name: "Laboratórios Informática",
    description: "Um espaço equipado com computadores, destinado à aulas de informática - Salas 1, 2 e 3",
    x: 19.75,
    y: 71.3,
    category: "Aulas Informática",
    color: "bg-green-900",
    visible: true,
  },
  {
    id: "21",
    name: "Sala 4",
    description: "Ambiente Pedagógico convencional, destinado à aulas teóricas gerais",
    x: 30.42,
    y: 71.3,
    category: "Ambiente Pedagógico",
    color: "bg-gray-900",
    visible: true,
  },
  {
    id: "22",
    name: "Sala 5",
    description: "Ambiente Pedagógico convencional, destinado à aulas teóricas gerais",
    x: 40.33,
    y: 71.3,
    category: "Ambiente Pedagógico",
    color: "bg-gray-900",
    visible: true,
  },
  {
    id: "23",
    name: "Laboratório Informática",
    description: "Um espaço equipado com computadores, destinado à aulas de informática - Sala 6",
    x: 50.01,
    y: 77.38,
    category: "Aulas Informática",
    color: "bg-green-900",
    visible: true,
  },
  {
    id: "24",
    name: "Laboratório Informática",
    description: "Um espaço equipado com computadores, destinado à aulas de informática - Salas 7",
    x: 60.35,
    y: 74,
    category: "Aulas Informática",
    color: "bg-green-900",
    visible: true,
  },
  {
    id: "25",
    name: "Mesas Circulação",
    description: "Um espaço com mesas livres, ideais para descanso, alimentação, entre outros",
    x: 37.55,
    y: 66,
    category: "Descanso",
    color: "bg-green-200",
    visible: true,
  },
  {
    id: "26",
    name: "Elevador",
    description: "Elevador de acesso ao primeiro e demais andares",
    x: 38,
    y: 38,
    category: "Acesso",
    color: "bg-blue-500",
    visible: true,
  },
  {
    id: "27",
    name: "Rampa",
    description: "Rampa de acesso ao primeiro e demais andares",
    x: 26.63,
    y: 35,
    category: "Acesso",
    color: "bg-blue-500",
    visible: true,
  },
]